version: "3.7"

services:
    app:
        image: ghcr.io/eveisesi/skillboard:v0.0.1
        restart: unless-stopped
        container_name: skillboard-app
        environment:
            - "USER_AGENT=Skillz Development || David Davaham Tweetfleet: @DoubleD"
            - REDIS_HOST=redis:54410
            - REDIS_PASS
            - MYSQL_HOST=mysql:54420
            - MYSQL_DB=skillz
            - MYSQL_USER=skillz
            - MYSQL_PASSWORD
            - LOG_LEVEL=info
            - EVE_JWKS_URI=https://login.eveonline.com/oauth/jwks
            - EVE_CLIENT_ID
            - EVE_CLIENT_SECRET
            - SERVER_PORT
            - AUTH_KEY
            - AUTH_EXPIRY
            - ENVIRONMENT
    redis:
        image: redis:6.2.5
        restart: unless-stopped
        container_name: skillboard-redis
        environment:
            - REDIS_PASS
        ports:
            - "54410:6379"
        command: >
            ./init_redis.sh
        volumes:
            - ./.config/redis/scripts/init_redis.sh:/data/init_redis.sh
            - ./.config/redis/tmpl_redis.conf:/data/tmpl_redis.conf
            - skillboard-cache:/data
    mysql:
        image: mysql:5.7
        restart: unless-stopped
        container_name: skillboard-mysql
        environment:
            - MYSQL_DATABASE=skillz
            - MYSQL_USER=skillz
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
        ports:
            - "54420:3306"
        volumes:
            - skillboard-mysql:/var/lib/mysql
            - ./.config/mysql/skillz.conf:/etc/mysql/skillz.conf
volumes:
    skillboard-cache:
    skillboard-mysql: