version: "3.7"

services:
    server:
        image: ghcr.io/eveisesi/skillboard/skillboard-api:0.2.0-rc4
        restart: unless-stopped
        container_name: skillboard-server
        environment:
            - USER_AGENT
            - REDIS_HOST
            - REDIS_PASS
            - MYSQL_HOST
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - LOG_LEVEL
            - EVE_CLIENT_ID
            - EVE_CLIENT_SECRET
            - EVE_CALLBACK_URI
            - ENVIRONMENT
        command: /app/skillboard-api buffalo
        ports:
           - "54400:54400"
    processor:
        image: ghcr.io/eveisesi/skillboard/skillboard-api:0.2.0-rc4
        restart: unless-stopped
        container_name: skillboard-processor
        environment:
            - USER_AGENT
            - REDIS_HOST
            - REDIS_PASS
            - MYSQL_HOST
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - LOG_LEVEL
            - EVE_CLIENT_ID
            - EVE_CLIENT_SECRET
            - EVE_CALLBACK_URI
            - ENVIRONMENT
        command: /app/skillboard-api processor
    cron:
        image: ghcr.io/eveisesi/skillboard/skillboard-api:0.2.0-rc4
        restart: unless-stopped
        container_name: skillboard-cron
        environment:
            - USER_AGENT
            - REDIS_HOST
            - REDIS_PASS
            - MYSQL_HOST
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - LOG_LEVEL
            - EVE_CLIENT_ID
            - EVE_CLIENT_SECRET
            - EVE_CALLBACK_URI
            - ENVIRONMENT
        command: /app/skillboard-api cron
    redis:
        image: redis:6.2.5
        restart: unless-stopped
        container_name: skillboard-redis
        environment:
            - REDIS_PASS
        ports:
            - "54410:6379"
        command: >
            ./init_redis.sh
        volumes:
            - ./.config/redis/scripts/init_redis.sh:/data/init_redis.sh
            - ./.config/redis/tmpl_redis.conf:/data/tmpl_redis.conf
            - skillboard-cache:/data
    mysql:
        image: mysql:5.7
        restart: unless-stopped
        container_name: skillboard-mysql
        environment:
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
        ports:
            - "54420:3306"
        volumes:
            - skillboard-mysql:/var/lib/mysql
            - ./.config/mysql/skillz.conf:/etc/mysql/skillz.conf
volumes:
    skillboard-cache:
    skillboard-mysql: