CREATE TABLE `member_wallet_journals` (
    `member_id` INT UNSIGNED NOT NULL,
    `journal_id` BIGINT UNSIGNED NOT NULL,
    `ref_type` VARCHAR(128) NOT NULL,
    `context_id` BIGINT UNSIGNED NULL DEFAULT NULL,
    `context_type` VARCHAR(128) NULL DEFAULT NULL,
    `description` VARCHAR(255) NOT NULL,
    `reason` VARCHAR(255) NULL DEFAULT NULL,
    `first_party_id` INT UNSIGNED NULL DEFAULT NULL,
    `first_party_type` VARCHAR(64) NULL DEFAULT NULL,
    `second_party_id` INT UNSIGNED NULL DEFAULT NULL,
    `second_party_type` VARCHAR(64) NULL DEFAULT NULL,
    `amount` FLOAT NULL DEFAULT NULL,
    `balance` FLOAT NULL DEFAULT NULL,
    `tax` FLOAT NULL DEFAULT NULL,
    `tax_receiver_id` INT UNSIGNED NULL DEFAULT NULL,
    `date` TIMESTAMP NOT NULL,
    `created_at` TIMESTAMP NOT NULL,
    `updated_at` TIMESTAMP NOT NULL,
    PRIMARY KEY (`member_id`, `journal_id`) USING BTREE,
    INDEX `member_wallet_journals_context_id` (`context_id`) USING BTREE,
    INDEX `member_wallet_journals_context_type` (`context_type`) USING BTREE,
    INDEX `member_wallet_journals_first_party_id` (`first_party_id`) USING BTREE,
    INDEX `member_wallet_journals_first_party_type` (`first_party_type`) USING BTREE,
    INDEX `member_wallet_journals_second_party_id` (`second_party_id`) USING BTREE,
    INDEX `member_wallet_journals_second_party_type` (`second_party_type`) USING BTREE,
    CONSTRAINT `member_wallet_journals_member_id_foreign` FOREIGN KEY (`member_id`) REFERENCES `athena`.`members` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
) COLLATE = 'utf8mb4_unicode_ci' ENGINE = InnoDB;