// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var TableNames = struct {
	Alliances                   string
	Bloodlines                  string
	CharacterAttributes         string
	CharacterCloneMeta          string
	CharacterContacts           string
	CharacterCorporationHistory string
	CharacterFlyableShips       string
	CharacterHomeClone          string
	CharacterImplants           string
	CharacterJumpClones         string
	CharacterSkillMeta          string
	CharacterSkillqueue         string
	CharacterSkills             string
	Characters                  string
	Corporations                string
	Etags                       string
	Factions                    string
	MapConstellations           string
	MapRegions                  string
	MapSolarSystems             string
	MapStations                 string
	MapStructures               string
	Races                       string
	TypeAttributes              string
	TypeCategories              string
	TypeGroups                  string
	Types                       string
	UserSettings                string
	Users                       string
}{
	Alliances:                   "alliances",
	Bloodlines:                  "bloodlines",
	CharacterAttributes:         "character_attributes",
	CharacterCloneMeta:          "character_clone_meta",
	CharacterContacts:           "character_contacts",
	CharacterCorporationHistory: "character_corporation_history",
	CharacterFlyableShips:       "character_flyable_ships",
	CharacterHomeClone:          "character_home_clone",
	CharacterImplants:           "character_implants",
	CharacterJumpClones:         "character_jump_clones",
	CharacterSkillMeta:          "character_skill_meta",
	CharacterSkillqueue:         "character_skillqueue",
	CharacterSkills:             "character_skills",
	Characters:                  "characters",
	Corporations:                "corporations",
	Etags:                       "etags",
	Factions:                    "factions",
	MapConstellations:           "map_constellations",
	MapRegions:                  "map_regions",
	MapSolarSystems:             "map_solar_systems",
	MapStations:                 "map_stations",
	MapStructures:               "map_structures",
	Races:                       "races",
	TypeAttributes:              "type_attributes",
	TypeCategories:              "type_categories",
	TypeGroups:                  "type_groups",
	Types:                       "types",
	UserSettings:                "user_settings",
	Users:                       "users",
}
