// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// CharacterHomeClone is an object representing the database table.
type CharacterHomeClone struct {
	CharacterID  uint64    `boil:"character_id" json:"character_id" toml:"character_id" yaml:"character_id"`
	LocationID   uint64    `boil:"location_id" json:"location_id" toml:"location_id" yaml:"location_id"`
	LocationType string    `boil:"location_type" json:"location_type" toml:"location_type" yaml:"location_type"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *characterHomeCloneR `boil:"r" json:"r" toml:"r" yaml:"r"`
	L characterHomeCloneL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CharacterHomeCloneColumns = struct {
	CharacterID  string
	LocationID   string
	LocationType string
	CreatedAt    string
	UpdatedAt    string
}{
	CharacterID:  "character_id",
	LocationID:   "location_id",
	LocationType: "location_type",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var CharacterHomeCloneTableColumns = struct {
	CharacterID  string
	LocationID   string
	LocationType string
	CreatedAt    string
	UpdatedAt    string
}{
	CharacterID:  "character_home_clone.character_id",
	LocationID:   "character_home_clone.location_id",
	LocationType: "character_home_clone.location_type",
	CreatedAt:    "character_home_clone.created_at",
	UpdatedAt:    "character_home_clone.updated_at",
}

// Generated where

var CharacterHomeCloneWhere = struct {
	CharacterID  whereHelperuint64
	LocationID   whereHelperuint64
	LocationType whereHelperstring
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
}{
	CharacterID:  whereHelperuint64{field: "`character_home_clone`.`character_id`"},
	LocationID:   whereHelperuint64{field: "`character_home_clone`.`location_id`"},
	LocationType: whereHelperstring{field: "`character_home_clone`.`location_type`"},
	CreatedAt:    whereHelpertime_Time{field: "`character_home_clone`.`created_at`"},
	UpdatedAt:    whereHelpertime_Time{field: "`character_home_clone`.`updated_at`"},
}

// CharacterHomeCloneRels is where relationship names are stored.
var CharacterHomeCloneRels = struct {
	Character string
}{
	Character: "Character",
}

// characterHomeCloneR is where relationships are stored.
type characterHomeCloneR struct {
	Character *User `boil:"Character" json:"Character" toml:"Character" yaml:"Character"`
}

// NewStruct creates a new relationship struct
func (*characterHomeCloneR) NewStruct() *characterHomeCloneR {
	return &characterHomeCloneR{}
}

// characterHomeCloneL is where Load methods for each relationship are stored.
type characterHomeCloneL struct{}

var (
	characterHomeCloneAllColumns            = []string{"character_id", "location_id", "location_type", "created_at", "updated_at"}
	characterHomeCloneColumnsWithoutDefault = []string{"character_id", "location_id", "location_type", "created_at", "updated_at"}
	characterHomeCloneColumnsWithDefault    = []string{}
	characterHomeClonePrimaryKeyColumns     = []string{"character_id"}
)

type (
	// CharacterHomeCloneSlice is an alias for a slice of pointers to CharacterHomeClone.
	// This should almost always be used instead of []CharacterHomeClone.
	CharacterHomeCloneSlice []*CharacterHomeClone
	// CharacterHomeCloneHook is the signature for custom CharacterHomeClone hook methods
	CharacterHomeCloneHook func(context.Context, boil.ContextExecutor, *CharacterHomeClone) error

	characterHomeCloneQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	characterHomeCloneType                 = reflect.TypeOf(&CharacterHomeClone{})
	characterHomeCloneMapping              = queries.MakeStructMapping(characterHomeCloneType)
	characterHomeClonePrimaryKeyMapping, _ = queries.BindMapping(characterHomeCloneType, characterHomeCloneMapping, characterHomeClonePrimaryKeyColumns)
	characterHomeCloneInsertCacheMut       sync.RWMutex
	characterHomeCloneInsertCache          = make(map[string]insertCache)
	characterHomeCloneUpdateCacheMut       sync.RWMutex
	characterHomeCloneUpdateCache          = make(map[string]updateCache)
	characterHomeCloneUpsertCacheMut       sync.RWMutex
	characterHomeCloneUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var characterHomeCloneBeforeInsertHooks []CharacterHomeCloneHook
var characterHomeCloneBeforeUpdateHooks []CharacterHomeCloneHook
var characterHomeCloneBeforeDeleteHooks []CharacterHomeCloneHook
var characterHomeCloneBeforeUpsertHooks []CharacterHomeCloneHook

var characterHomeCloneAfterInsertHooks []CharacterHomeCloneHook
var characterHomeCloneAfterSelectHooks []CharacterHomeCloneHook
var characterHomeCloneAfterUpdateHooks []CharacterHomeCloneHook
var characterHomeCloneAfterDeleteHooks []CharacterHomeCloneHook
var characterHomeCloneAfterUpsertHooks []CharacterHomeCloneHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *CharacterHomeClone) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range characterHomeCloneBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *CharacterHomeClone) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range characterHomeCloneBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *CharacterHomeClone) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range characterHomeCloneBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *CharacterHomeClone) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range characterHomeCloneBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *CharacterHomeClone) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range characterHomeCloneAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *CharacterHomeClone) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range characterHomeCloneAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *CharacterHomeClone) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range characterHomeCloneAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *CharacterHomeClone) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range characterHomeCloneAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *CharacterHomeClone) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range characterHomeCloneAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCharacterHomeCloneHook registers your hook function for all future operations.
func AddCharacterHomeCloneHook(hookPoint boil.HookPoint, characterHomeCloneHook CharacterHomeCloneHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		characterHomeCloneBeforeInsertHooks = append(characterHomeCloneBeforeInsertHooks, characterHomeCloneHook)
	case boil.BeforeUpdateHook:
		characterHomeCloneBeforeUpdateHooks = append(characterHomeCloneBeforeUpdateHooks, characterHomeCloneHook)
	case boil.BeforeDeleteHook:
		characterHomeCloneBeforeDeleteHooks = append(characterHomeCloneBeforeDeleteHooks, characterHomeCloneHook)
	case boil.BeforeUpsertHook:
		characterHomeCloneBeforeUpsertHooks = append(characterHomeCloneBeforeUpsertHooks, characterHomeCloneHook)
	case boil.AfterInsertHook:
		characterHomeCloneAfterInsertHooks = append(characterHomeCloneAfterInsertHooks, characterHomeCloneHook)
	case boil.AfterSelectHook:
		characterHomeCloneAfterSelectHooks = append(characterHomeCloneAfterSelectHooks, characterHomeCloneHook)
	case boil.AfterUpdateHook:
		characterHomeCloneAfterUpdateHooks = append(characterHomeCloneAfterUpdateHooks, characterHomeCloneHook)
	case boil.AfterDeleteHook:
		characterHomeCloneAfterDeleteHooks = append(characterHomeCloneAfterDeleteHooks, characterHomeCloneHook)
	case boil.AfterUpsertHook:
		characterHomeCloneAfterUpsertHooks = append(characterHomeCloneAfterUpsertHooks, characterHomeCloneHook)
	}
}

// OneG returns a single characterHomeClone record from the query using the global executor.
func (q characterHomeCloneQuery) OneG(ctx context.Context) (*CharacterHomeClone, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single characterHomeClone record from the query.
func (q characterHomeCloneQuery) One(ctx context.Context, exec boil.ContextExecutor) (*CharacterHomeClone, error) {
	o := &CharacterHomeClone{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: failed to execute a one query for character_home_clone")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all CharacterHomeClone records from the query using the global executor.
func (q characterHomeCloneQuery) AllG(ctx context.Context) (CharacterHomeCloneSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all CharacterHomeClone records from the query.
func (q characterHomeCloneQuery) All(ctx context.Context, exec boil.ContextExecutor) (CharacterHomeCloneSlice, error) {
	var o []*CharacterHomeClone

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "boiler: failed to assign all query results to CharacterHomeClone slice")
	}

	if len(characterHomeCloneAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all CharacterHomeClone records in the query, and panics on error.
func (q characterHomeCloneQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all CharacterHomeClone records in the query.
func (q characterHomeCloneQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to count character_home_clone rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table, and panics on error.
func (q characterHomeCloneQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q characterHomeCloneQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "boiler: failed to check if character_home_clone exists")
	}

	return count > 0, nil
}

// Character pointed to by the foreign key.
func (o *CharacterHomeClone) Character(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`character_id` = ?", o.CharacterID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "`users`")

	return query
}

// LoadCharacter allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (characterHomeCloneL) LoadCharacter(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCharacterHomeClone interface{}, mods queries.Applicator) error {
	var slice []*CharacterHomeClone
	var object *CharacterHomeClone

	if singular {
		object = maybeCharacterHomeClone.(*CharacterHomeClone)
	} else {
		slice = *maybeCharacterHomeClone.(*[]*CharacterHomeClone)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &characterHomeCloneR{}
		}
		args = append(args, object.CharacterID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &characterHomeCloneR{}
			}

			for _, a := range args {
				if a == obj.CharacterID {
					continue Outer
				}
			}

			args = append(args, obj.CharacterID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.character_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(characterHomeCloneAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Character = foreign
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CharacterID == foreign.CharacterID {
				local.R.Character = foreign
				break
			}
		}
	}

	return nil
}

// SetCharacterG of the characterHomeClone to the related item.
// Sets o.R.Character to related.
// Adds o to related.R.CharacterCharacterHomeClone.
// Uses the global database handle.
func (o *CharacterHomeClone) SetCharacterG(ctx context.Context, insert bool, related *User) error {
	return o.SetCharacter(ctx, boil.GetContextDB(), insert, related)
}

// SetCharacter of the characterHomeClone to the related item.
// Sets o.R.Character to related.
// Adds o to related.R.CharacterCharacterHomeClone.
func (o *CharacterHomeClone) SetCharacter(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `character_home_clone` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"character_id"}),
		strmangle.WhereClause("`", "`", 0, characterHomeClonePrimaryKeyColumns),
	)
	values := []interface{}{related.CharacterID, o.CharacterID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CharacterID = related.CharacterID
	if o.R == nil {
		o.R = &characterHomeCloneR{
			Character: related,
		}
	} else {
		o.R.Character = related
	}

	if related.R == nil {
		related.R = &userR{
			CharacterCharacterHomeClone: o,
		}
	} else {
		related.R.CharacterCharacterHomeClone = o
	}

	return nil
}

// CharacterHomeClones retrieves all the records using an executor.
func CharacterHomeClones(mods ...qm.QueryMod) characterHomeCloneQuery {
	mods = append(mods, qm.From("`character_home_clone`"))
	return characterHomeCloneQuery{NewQuery(mods...)}
}

// FindCharacterHomeCloneG retrieves a single record by ID.
func FindCharacterHomeCloneG(ctx context.Context, characterID uint64, selectCols ...string) (*CharacterHomeClone, error) {
	return FindCharacterHomeClone(ctx, boil.GetContextDB(), characterID, selectCols...)
}

// FindCharacterHomeClone retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCharacterHomeClone(ctx context.Context, exec boil.ContextExecutor, characterID uint64, selectCols ...string) (*CharacterHomeClone, error) {
	characterHomeCloneObj := &CharacterHomeClone{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `character_home_clone` where `character_id`=?", sel,
	)

	q := queries.Raw(query, characterID)

	err := q.Bind(ctx, exec, characterHomeCloneObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: unable to select from character_home_clone")
	}

	if err = characterHomeCloneObj.doAfterSelectHooks(ctx, exec); err != nil {
		return characterHomeCloneObj, err
	}

	return characterHomeCloneObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *CharacterHomeClone) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CharacterHomeClone) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no character_home_clone provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(characterHomeCloneColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	characterHomeCloneInsertCacheMut.RLock()
	cache, cached := characterHomeCloneInsertCache[key]
	characterHomeCloneInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			characterHomeCloneAllColumns,
			characterHomeCloneColumnsWithDefault,
			characterHomeCloneColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(characterHomeCloneType, characterHomeCloneMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(characterHomeCloneType, characterHomeCloneMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `character_home_clone` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `character_home_clone` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `character_home_clone` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, characterHomeClonePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "boiler: unable to insert into character_home_clone")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.CharacterID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to populate default values for character_home_clone")
	}

CacheNoHooks:
	if !cached {
		characterHomeCloneInsertCacheMut.Lock()
		characterHomeCloneInsertCache[key] = cache
		characterHomeCloneInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single CharacterHomeClone record using the global executor.
// See Update for more documentation.
func (o *CharacterHomeClone) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the CharacterHomeClone.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CharacterHomeClone) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	characterHomeCloneUpdateCacheMut.RLock()
	cache, cached := characterHomeCloneUpdateCache[key]
	characterHomeCloneUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			characterHomeCloneAllColumns,
			characterHomeClonePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("boiler: unable to update character_home_clone, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `character_home_clone` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, characterHomeClonePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(characterHomeCloneType, characterHomeCloneMapping, append(wl, characterHomeClonePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update character_home_clone row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by update for character_home_clone")
	}

	if !cached {
		characterHomeCloneUpdateCacheMut.Lock()
		characterHomeCloneUpdateCache[key] = cache
		characterHomeCloneUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q characterHomeCloneQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q characterHomeCloneQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all for character_home_clone")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected for character_home_clone")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o CharacterHomeCloneSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CharacterHomeCloneSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("boiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), characterHomeClonePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `character_home_clone` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, characterHomeClonePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all in characterHomeClone slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected all in update all characterHomeClone")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *CharacterHomeClone) UpsertG(ctx context.Context, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateColumns, insertColumns)
}

var mySQLCharacterHomeCloneUniqueColumns = []string{
	"character_id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CharacterHomeClone) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no character_home_clone provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(characterHomeCloneColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLCharacterHomeCloneUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	characterHomeCloneUpsertCacheMut.RLock()
	cache, cached := characterHomeCloneUpsertCache[key]
	characterHomeCloneUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			characterHomeCloneAllColumns,
			characterHomeCloneColumnsWithDefault,
			characterHomeCloneColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			characterHomeCloneAllColumns,
			characterHomeClonePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("boiler: unable to upsert character_home_clone, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`character_home_clone`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `character_home_clone` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(characterHomeCloneType, characterHomeCloneMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(characterHomeCloneType, characterHomeCloneMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "boiler: unable to upsert for character_home_clone")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(characterHomeCloneType, characterHomeCloneMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to retrieve unique values for character_home_clone")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to populate default values for character_home_clone")
	}

CacheNoHooks:
	if !cached {
		characterHomeCloneUpsertCacheMut.Lock()
		characterHomeCloneUpsertCache[key] = cache
		characterHomeCloneUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single CharacterHomeClone record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *CharacterHomeClone) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single CharacterHomeClone record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CharacterHomeClone) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("boiler: no CharacterHomeClone provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), characterHomeClonePrimaryKeyMapping)
	sql := "DELETE FROM `character_home_clone` WHERE `character_id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete from character_home_clone")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by delete for character_home_clone")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q characterHomeCloneQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q characterHomeCloneQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("boiler: no characterHomeCloneQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from character_home_clone")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for character_home_clone")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o CharacterHomeCloneSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CharacterHomeCloneSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(characterHomeCloneBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), characterHomeClonePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `character_home_clone` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, characterHomeClonePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from characterHomeClone slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for character_home_clone")
	}

	if len(characterHomeCloneAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *CharacterHomeClone) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("boiler: no CharacterHomeClone provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CharacterHomeClone) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCharacterHomeClone(ctx, exec, o.CharacterID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CharacterHomeCloneSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("boiler: empty CharacterHomeCloneSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CharacterHomeCloneSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CharacterHomeCloneSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), characterHomeClonePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `character_home_clone`.* FROM `character_home_clone` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, characterHomeClonePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to reload all in CharacterHomeCloneSlice")
	}

	*o = slice

	return nil
}

// CharacterHomeCloneExistsG checks if the CharacterHomeClone row exists.
func CharacterHomeCloneExistsG(ctx context.Context, characterID uint64) (bool, error) {
	return CharacterHomeCloneExists(ctx, boil.GetContextDB(), characterID)
}

// CharacterHomeCloneExists checks if the CharacterHomeClone row exists.
func CharacterHomeCloneExists(ctx context.Context, exec boil.ContextExecutor, characterID uint64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `character_home_clone` where `character_id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, characterID)
	}
	row := exec.QueryRowContext(ctx, sql, characterID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "boiler: unable to check if character_home_clone exists")
	}

	return exists, nil
}
